### ISSUE TITLE
在AOSP的手机上遇到一个问题

### ISSUE THREAD

**Issue by tangsilian** [xxxyanchenxxx/SigKill#1]
07-10 02:09:34.319 3040-3040/com.iviroot.root W/System.err: com.yc.pm.ReflectException: java.lang.ClassNotFoundException: android.webkit.IWebViewUpdateService$Stub
07-10 02:09:34.329 3040-3040/com.iviroot.root W/System.err:     at com.yc.pm.Reflect.forName(Reflect.java:200)
07-10 02:09:34.329 3040-3040/com.iviroot.root W/System.err:     at com.yc.pm.Reflect.on(Reflect.java:42)
07-10 02:09:34.329 3040-3040/com.iviroot.root W/System.err:     at com.yc.pm.WebViewUpdateServiceStub.getInterface(WebViewUpdateServiceStub.java:31)
07-10 02:09:34.329 3040-3040/com.iviroot.root W/System.err:     at com.yc.pm.WebViewUpdateServiceStub.<init>(WebViewUpdateServiceStub.java:18)
07-10 02:09:34.329 3040-3040/com.iviroot.root W/System.err:     at com.yc.pm.WebViewUpdateServiceStub.replaceService(WebViewUpdateServiceStub.java:24)

**Comment by xxxyanchenxxx** [comment]
@tangsilian fixed by https://github.com/xxxyanchenxxx/SigKill/commit/db2aac31a05903c8a59c0e0789ef49851dbe95d1
